<?xml version="1.0" encoding="utf-8"?><Database Name="mastermind" Class="TeraArticleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mastermind;Initial Catalog=mastermind;Persist Security Info=True;User ID=sa" SettingsObjectName="TeraCrawler.Properties.Settings" SettingsPropertyName="mastermindConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Articles" Member="Articles">
    <Type Name="Article">
      <Column Name="ArticleAutoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Game" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetSite" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArticleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="RawHtml" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CrawledTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ContentHtml" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ArticleWrittenTime" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Log">
      <Column Name="LogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="LogType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CheckPoints" Member="CheckPoints">
    <Type Name="CheckPoint">
      <Column Name="AnalysisPhase" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProcessedArticleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="CommentAutoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentCommentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArticleAutoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ContentHtml" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CommentWrittenTime" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="LikeCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DislikeCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>